-- Secuencias para los IDs automaticos

CREATE SEQUENCE SEQ_TIPOS_MATERIAL START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CATEGORIAS     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATERIALES     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRESTAMOS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MULTAS         START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDITORIA_LOG  START WITH 1 INCREMENT BY 1 NOCACHE;
