-- Especificaciones de paquetes

-- PKG_TIPOS_MATERIAL
CREATE OR REPLACE PACKAGE PKG_TIPOS_MATERIAL AS

    PROCEDURE CREAR_TIPO_MATERIAL(
        P_NOMBRE      IN TIPOS_MATERIAL.NOMBRE%TYPE,
        P_DESCRIPCION IN TIPOS_MATERIAL.DESCRIPCION%TYPE
    );

    PROCEDURE ACTUALIZAR_TIPO_MATERIAL(
        P_ID_TIPO_MATERIAL IN TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE,
        P_NOMBRE           IN TIPOS_MATERIAL.NOMBRE%TYPE,
        P_DESCRIPCION      IN TIPOS_MATERIAL.DESCRIPCION%TYPE
    );

    PROCEDURE INACTIVAR_TIPO_MATERIAL(
        P_ID_TIPO_MATERIAL IN TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE
    );

    PROCEDURE OBTENER_TIPO_MATERIAL(
        P_ID_TIPO_MATERIAL IN  TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE,
        P_RESULTADO        OUT SYS_REFCURSOR
    );

    PROCEDURE LISTAR_TIPOS_MATERIAL(
        P_RESULTADO OUT SYS_REFCURSOR
    );

END PKG_TIPOS_MATERIAL;
/

-- PKG_CATEGORIAS
CREATE OR REPLACE PACKAGE PKG_CATEGORIAS AS

    PROCEDURE CREAR_CATEGORIA(
        P_NOMBRE      IN CATEGORIAS.NOMBRE%TYPE,
        P_DESCRIPCION IN CATEGORIAS.DESCRIPCION%TYPE
    );

    PROCEDURE ACTUALIZAR_CATEGORIA(
        P_ID_CATEGORIA IN CATEGORIAS.ID_CATEGORIA%TYPE,
        P_NOMBRE       IN CATEGORIAS.NOMBRE%TYPE,
        P_DESCRIPCION  IN CATEGORIAS.DESCRIPCION%TYPE
    );

    PROCEDURE INACTIVAR_CATEGORIA(
        P_ID_CATEGORIA IN CATEGORIAS.ID_CATEGORIA%TYPE
    );

    PROCEDURE OBTENER_CATEGORIA(
        P_ID_CATEGORIA IN  CATEGORIAS.ID_CATEGORIA%TYPE,
        P_RESULTADO    OUT SYS_REFCURSOR
    );

    PROCEDURE LISTAR_CATEGORIAS(
        P_RESULTADO OUT SYS_REFCURSOR
    );

END PKG_CATEGORIAS;
/

-- PKG_USUARIOS
CREATE OR REPLACE PACKAGE PKG_USUARIOS AS

    PROCEDURE CREAR_USUARIO(
        P_CEDULA    IN USUARIOS.CEDULA%TYPE,
        P_NOMBRE    IN USUARIOS.NOMBRE%TYPE,
        P_APELLIDOS IN USUARIOS.APELLIDOS%TYPE,
        P_CORREO    IN USUARIOS.CORREO%TYPE,
        P_TELEFONO  IN USUARIOS.TELEFONO%TYPE
    );

    PROCEDURE ACTUALIZAR_USUARIO(
        P_CEDULA    IN USUARIOS.CEDULA%TYPE,
        P_NOMBRE    IN USUARIOS.NOMBRE%TYPE,
        P_APELLIDOS IN USUARIOS.APELLIDOS%TYPE,
        P_CORREO    IN USUARIOS.CORREO%TYPE,
        P_TELEFONO  IN USUARIOS.TELEFONO%TYPE
    );

    PROCEDURE INACTIVAR_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE
    );

    PROCEDURE OBTENER_USUARIO(
        P_CEDULA    IN  USUARIOS.CEDULA%TYPE,
        P_RESULTADO OUT SYS_REFCURSOR
    );

    PROCEDURE LISTAR_USUARIOS(
        P_RESULTADO OUT SYS_REFCURSOR
    );

END PKG_USUARIOS;
/

-- PKG_MATERIALES
CREATE OR REPLACE PACKAGE PKG_MATERIALES AS

    PROCEDURE CREAR_MATERIAL(
        P_TITULO           IN MATERIALES.TITULO%TYPE,
        P_AUTOR            IN MATERIALES.AUTOR%TYPE,
        P_EDITORIAL        IN MATERIALES.EDITORIAL%TYPE,
        P_ANIO_PUBLICACION IN MATERIALES.ANIO_PUBLICACION%TYPE,
        P_CODIGO_ISBN      IN MATERIALES.CODIGO_ISBN%TYPE,
        P_ID_TIPO_MATERIAL IN MATERIALES.ID_TIPO_MATERIAL%TYPE,
        P_ID_CATEGORIA     IN MATERIALES.ID_CATEGORIA%TYPE
    );

    PROCEDURE ACTUALIZAR_MATERIAL(
        P_ID_MATERIAL      IN MATERIALES.ID_MATERIAL%TYPE,
        P_TITULO           IN MATERIALES.TITULO%TYPE,
        P_AUTOR            IN MATERIALES.AUTOR%TYPE,
        P_EDITORIAL        IN MATERIALES.EDITORIAL%TYPE,
        P_ANIO_PUBLICACION IN MATERIALES.ANIO_PUBLICACION%TYPE,
        P_CODIGO_ISBN      IN MATERIALES.CODIGO_ISBN%TYPE,
        P_ID_TIPO_MATERIAL IN MATERIALES.ID_TIPO_MATERIAL%TYPE,
        P_ID_CATEGORIA     IN MATERIALES.ID_CATEGORIA%TYPE
    );

    PROCEDURE INACTIVAR_MATERIAL(
        P_ID_MATERIAL IN MATERIALES.ID_MATERIAL%TYPE
    );

    PROCEDURE OBTENER_MATERIAL(
        P_ID_MATERIAL IN  MATERIALES.ID_MATERIAL%TYPE,
        P_RESULTADO   OUT SYS_REFCURSOR
    );

    PROCEDURE LISTAR_MATERIALES(
        P_RESULTADO OUT SYS_REFCURSOR
    );

    PROCEDURE BUSCAR_MATERIALES(
        P_TEXTO     IN  VARCHAR2,
        P_RESULTADO OUT SYS_REFCURSOR
    );

    FUNCTION FN_MATERIAL_DISPONIBLE(
        P_ID_MATERIAL IN MATERIALES.ID_MATERIAL%TYPE
    ) RETURN NUMBER;

END PKG_MATERIALES;
/

-- PKG_PRESTAMOS
CREATE OR REPLACE PACKAGE PKG_PRESTAMOS AS

    PROCEDURE REGISTRAR_PRESTAMO(
        P_CEDULA                    IN PRESTAMOS.CEDULA%TYPE,
        P_ID_MATERIAL               IN PRESTAMOS.ID_MATERIAL%TYPE,
        P_FECHA_DEVOLUCION_ESPERADA IN PRESTAMOS.FECHA_DEVOLUCION_ESPERADA%TYPE
    );

    PROCEDURE REGISTRAR_DEVOLUCION(
        P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE
    );

    PROCEDURE ANULAR_PRESTAMO(
        P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE
    );

    PROCEDURE OBTENER_PRESTAMO(
        P_ID_PRESTAMO IN  PRESTAMOS.ID_PRESTAMO%TYPE,
        P_RESULTADO   OUT SYS_REFCURSOR
    );

    PROCEDURE LISTAR_PRESTAMOS(
        P_RESULTADO OUT SYS_REFCURSOR
    );

    PROCEDURE LISTAR_PRESTAMOS_ACTIVOS(
        P_RESULTADO OUT SYS_REFCURSOR
    );

    PROCEDURE LISTAR_HISTORIAL_USUARIO(
        P_CEDULA    IN  USUARIOS.CEDULA%TYPE,
        P_RESULTADO OUT SYS_REFCURSOR
    );

    FUNCTION FN_PRESTAMOS_ACTIVOS_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE
    ) RETURN NUMBER;

END PKG_PRESTAMOS;
/
