-- Cuerpos de paquetes

-- PKG_TIPOS_MATERIAL
CREATE OR REPLACE PACKAGE BODY PKG_TIPOS_MATERIAL AS

    PROCEDURE CREAR_TIPO_MATERIAL(
        P_NOMBRE      IN TIPOS_MATERIAL.NOMBRE%TYPE,
        P_DESCRIPCION IN TIPOS_MATERIAL.DESCRIPCION%TYPE
    ) IS
    BEGIN
        INSERT INTO TIPOS_MATERIAL (ID_TIPO_MATERIAL, NOMBRE, DESCRIPCION)
        VALUES (SEQ_TIPOS_MATERIAL.NEXTVAL, P_NOMBRE, P_DESCRIPCION);
    END CREAR_TIPO_MATERIAL;

    PROCEDURE ACTUALIZAR_TIPO_MATERIAL(
        P_ID_TIPO_MATERIAL IN TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE,
        P_NOMBRE           IN TIPOS_MATERIAL.NOMBRE%TYPE,
        P_DESCRIPCION      IN TIPOS_MATERIAL.DESCRIPCION%TYPE
    ) IS
    BEGIN
        UPDATE TIPOS_MATERIAL
        SET NOMBRE = P_NOMBRE, DESCRIPCION = P_DESCRIPCION
        WHERE ID_TIPO_MATERIAL = P_ID_TIPO_MATERIAL;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Tipo de material no encontrado.');
        END IF;
    END ACTUALIZAR_TIPO_MATERIAL;

    PROCEDURE INACTIVAR_TIPO_MATERIAL(
        P_ID_TIPO_MATERIAL IN TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE
    ) IS
    BEGIN
        UPDATE TIPOS_MATERIAL SET ESTADO = 'I'
        WHERE ID_TIPO_MATERIAL = P_ID_TIPO_MATERIAL;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'Tipo de material no encontrado.');
        END IF;
    END INACTIVAR_TIPO_MATERIAL;

    PROCEDURE OBTENER_TIPO_MATERIAL(
        P_ID_TIPO_MATERIAL IN  TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE,
        P_RESULTADO        OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT ID_TIPO_MATERIAL, NOMBRE, DESCRIPCION, ESTADO
            FROM TIPOS_MATERIAL
            WHERE ID_TIPO_MATERIAL = P_ID_TIPO_MATERIAL;
    END OBTENER_TIPO_MATERIAL;

    PROCEDURE LISTAR_TIPOS_MATERIAL(
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT ID_TIPO_MATERIAL, NOMBRE, DESCRIPCION, ESTADO
            FROM TIPOS_MATERIAL
            ORDER BY NOMBRE;
    END LISTAR_TIPOS_MATERIAL;

END PKG_TIPOS_MATERIAL;
/

-- PKG_CATEGORIAS
CREATE OR REPLACE PACKAGE BODY PKG_CATEGORIAS AS

    PROCEDURE CREAR_CATEGORIA(
        P_NOMBRE      IN CATEGORIAS.NOMBRE%TYPE,
        P_DESCRIPCION IN CATEGORIAS.DESCRIPCION%TYPE
    ) IS
    BEGIN
        INSERT INTO CATEGORIAS (ID_CATEGORIA, NOMBRE, DESCRIPCION)
        VALUES (SEQ_CATEGORIAS.NEXTVAL, P_NOMBRE, P_DESCRIPCION);
    END CREAR_CATEGORIA;

    PROCEDURE ACTUALIZAR_CATEGORIA(
        P_ID_CATEGORIA IN CATEGORIAS.ID_CATEGORIA%TYPE,
        P_NOMBRE       IN CATEGORIAS.NOMBRE%TYPE,
        P_DESCRIPCION  IN CATEGORIAS.DESCRIPCION%TYPE
    ) IS
    BEGIN
        UPDATE CATEGORIAS
        SET NOMBRE = P_NOMBRE, DESCRIPCION = P_DESCRIPCION
        WHERE ID_CATEGORIA = P_ID_CATEGORIA;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20003, 'Categoria no encontrada.');
        END IF;
    END ACTUALIZAR_CATEGORIA;

    PROCEDURE INACTIVAR_CATEGORIA(
        P_ID_CATEGORIA IN CATEGORIAS.ID_CATEGORIA%TYPE
    ) IS
    BEGIN
        UPDATE CATEGORIAS SET ESTADO = 'I'
        WHERE ID_CATEGORIA = P_ID_CATEGORIA;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20004, 'Categoria no encontrada.');
        END IF;
    END INACTIVAR_CATEGORIA;

    PROCEDURE OBTENER_CATEGORIA(
        P_ID_CATEGORIA IN  CATEGORIAS.ID_CATEGORIA%TYPE,
        P_RESULTADO    OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT ID_CATEGORIA, NOMBRE, DESCRIPCION, ESTADO
            FROM CATEGORIAS
            WHERE ID_CATEGORIA = P_ID_CATEGORIA;
    END OBTENER_CATEGORIA;

    PROCEDURE LISTAR_CATEGORIAS(
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT ID_CATEGORIA, NOMBRE, DESCRIPCION, ESTADO
            FROM CATEGORIAS
            ORDER BY NOMBRE;
    END LISTAR_CATEGORIAS;

END PKG_CATEGORIAS;
/

-- PKG_USUARIOS
CREATE OR REPLACE PACKAGE BODY PKG_USUARIOS AS

    PROCEDURE CREAR_USUARIO(
        P_CEDULA    IN USUARIOS.CEDULA%TYPE,
        P_NOMBRE    IN USUARIOS.NOMBRE%TYPE,
        P_APELLIDOS IN USUARIOS.APELLIDOS%TYPE,
        P_CORREO    IN USUARIOS.CORREO%TYPE,
        P_TELEFONO  IN USUARIOS.TELEFONO%TYPE
    ) IS
    BEGIN
        INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO)
        VALUES (P_CEDULA, P_NOMBRE, P_APELLIDOS, P_CORREO, P_TELEFONO);
    END CREAR_USUARIO;

    PROCEDURE ACTUALIZAR_USUARIO(
        P_CEDULA    IN USUARIOS.CEDULA%TYPE,
        P_NOMBRE    IN USUARIOS.NOMBRE%TYPE,
        P_APELLIDOS IN USUARIOS.APELLIDOS%TYPE,
        P_CORREO    IN USUARIOS.CORREO%TYPE,
        P_TELEFONO  IN USUARIOS.TELEFONO%TYPE
    ) IS
    BEGIN
        UPDATE USUARIOS
        SET NOMBRE = P_NOMBRE, APELLIDOS = P_APELLIDOS,
            CORREO = P_CORREO, TELEFONO = P_TELEFONO
        WHERE CEDULA = P_CEDULA;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20010, 'Usuario no encontrado.');
        END IF;
    END ACTUALIZAR_USUARIO;

    PROCEDURE INACTIVAR_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE
    ) IS
    BEGIN
        UPDATE USUARIOS SET ESTADO = 'I' WHERE CEDULA = P_CEDULA;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20011, 'Usuario no encontrado.');
        END IF;
    END INACTIVAR_USUARIO;

    PROCEDURE OBTENER_USUARIO(
        P_CEDULA    IN  USUARIOS.CEDULA%TYPE,
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO,
                   FECHA_REGISTRO, ESTADO
            FROM USUARIOS
            WHERE CEDULA = P_CEDULA;
    END OBTENER_USUARIO;

    PROCEDURE LISTAR_USUARIOS(
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO,
                   FECHA_REGISTRO, ESTADO
            FROM USUARIOS
            ORDER BY APELLIDOS, NOMBRE;
    END LISTAR_USUARIOS;

END PKG_USUARIOS;
/

-- PKG_MATERIALES
CREATE OR REPLACE PACKAGE BODY PKG_MATERIALES AS

    PROCEDURE CREAR_MATERIAL(
        P_TITULO           IN MATERIALES.TITULO%TYPE,
        P_AUTOR            IN MATERIALES.AUTOR%TYPE,
        P_EDITORIAL        IN MATERIALES.EDITORIAL%TYPE,
        P_ANIO_PUBLICACION IN MATERIALES.ANIO_PUBLICACION%TYPE,
        P_CODIGO_ISBN      IN MATERIALES.CODIGO_ISBN%TYPE,
        P_ID_TIPO_MATERIAL IN MATERIALES.ID_TIPO_MATERIAL%TYPE,
        P_ID_CATEGORIA     IN MATERIALES.ID_CATEGORIA%TYPE
    ) IS
    BEGIN
        INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL,
                                ANIO_PUBLICACION, CODIGO_ISBN,
                                ID_TIPO_MATERIAL, ID_CATEGORIA)
        VALUES (SEQ_MATERIALES.NEXTVAL, P_TITULO, P_AUTOR, P_EDITORIAL,
                P_ANIO_PUBLICACION, P_CODIGO_ISBN,
                P_ID_TIPO_MATERIAL, P_ID_CATEGORIA);
    END CREAR_MATERIAL;

    PROCEDURE ACTUALIZAR_MATERIAL(
        P_ID_MATERIAL      IN MATERIALES.ID_MATERIAL%TYPE,
        P_TITULO           IN MATERIALES.TITULO%TYPE,
        P_AUTOR            IN MATERIALES.AUTOR%TYPE,
        P_EDITORIAL        IN MATERIALES.EDITORIAL%TYPE,
        P_ANIO_PUBLICACION IN MATERIALES.ANIO_PUBLICACION%TYPE,
        P_CODIGO_ISBN      IN MATERIALES.CODIGO_ISBN%TYPE,
        P_ID_TIPO_MATERIAL IN MATERIALES.ID_TIPO_MATERIAL%TYPE,
        P_ID_CATEGORIA     IN MATERIALES.ID_CATEGORIA%TYPE
    ) IS
    BEGIN
        UPDATE MATERIALES
        SET TITULO = P_TITULO, AUTOR = P_AUTOR, EDITORIAL = P_EDITORIAL,
            ANIO_PUBLICACION = P_ANIO_PUBLICACION, CODIGO_ISBN = P_CODIGO_ISBN,
            ID_TIPO_MATERIAL = P_ID_TIPO_MATERIAL, ID_CATEGORIA = P_ID_CATEGORIA
        WHERE ID_MATERIAL = P_ID_MATERIAL;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20020, 'Material no encontrado.');
        END IF;
    END ACTUALIZAR_MATERIAL;

    PROCEDURE INACTIVAR_MATERIAL(
        P_ID_MATERIAL IN MATERIALES.ID_MATERIAL%TYPE
    ) IS
    BEGIN
        UPDATE MATERIALES SET ESTADO = 'INACTIVO'
        WHERE ID_MATERIAL = P_ID_MATERIAL;
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20021, 'Material no encontrado.');
        END IF;
    END INACTIVAR_MATERIAL;

    PROCEDURE OBTENER_MATERIAL(
        P_ID_MATERIAL IN  MATERIALES.ID_MATERIAL%TYPE,
        P_RESULTADO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT M.ID_MATERIAL, M.TITULO, M.AUTOR, M.EDITORIAL,
                   M.ANIO_PUBLICACION, M.CODIGO_ISBN,
                   M.ID_TIPO_MATERIAL, M.ID_CATEGORIA, M.ESTADO,
                   T.NOMBRE AS TIPO_NOMBRE, C.NOMBRE AS CATEGORIA_NOMBRE
            FROM MATERIALES M
            JOIN TIPOS_MATERIAL T ON M.ID_TIPO_MATERIAL = T.ID_TIPO_MATERIAL
            JOIN CATEGORIAS C    ON M.ID_CATEGORIA = C.ID_CATEGORIA
            WHERE M.ID_MATERIAL = P_ID_MATERIAL;
    END OBTENER_MATERIAL;

    PROCEDURE LISTAR_MATERIALES(
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT M.ID_MATERIAL, M.TITULO, M.AUTOR, M.EDITORIAL,
                   M.ANIO_PUBLICACION, M.CODIGO_ISBN,
                   M.ID_TIPO_MATERIAL, M.ID_CATEGORIA, M.ESTADO,
                   T.NOMBRE AS TIPO_NOMBRE, C.NOMBRE AS CATEGORIA_NOMBRE
            FROM MATERIALES M
            JOIN TIPOS_MATERIAL T ON M.ID_TIPO_MATERIAL = T.ID_TIPO_MATERIAL
            JOIN CATEGORIAS C    ON M.ID_CATEGORIA = C.ID_CATEGORIA
            ORDER BY M.TITULO;
    END LISTAR_MATERIALES;

    PROCEDURE BUSCAR_MATERIALES(
        P_TEXTO     IN  VARCHAR2,
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT M.ID_MATERIAL, M.TITULO, M.AUTOR, M.EDITORIAL,
                   M.ANIO_PUBLICACION, M.CODIGO_ISBN,
                   M.ID_TIPO_MATERIAL, M.ID_CATEGORIA, M.ESTADO,
                   T.NOMBRE AS TIPO_NOMBRE, C.NOMBRE AS CATEGORIA_NOMBRE
            FROM MATERIALES M
            JOIN TIPOS_MATERIAL T ON M.ID_TIPO_MATERIAL = T.ID_TIPO_MATERIAL
            JOIN CATEGORIAS C    ON M.ID_CATEGORIA = C.ID_CATEGORIA
            WHERE UPPER(M.TITULO) LIKE '%' || UPPER(P_TEXTO) || '%'
               OR UPPER(M.AUTOR)  LIKE '%' || UPPER(P_TEXTO) || '%'
               OR UPPER(C.NOMBRE) LIKE '%' || UPPER(P_TEXTO) || '%'
            ORDER BY M.TITULO;
    END BUSCAR_MATERIALES;

    FUNCTION FN_MATERIAL_DISPONIBLE(
        P_ID_MATERIAL IN MATERIALES.ID_MATERIAL%TYPE
    ) RETURN NUMBER IS
        V_ESTADO MATERIALES.ESTADO%TYPE;
    BEGIN
        SELECT ESTADO INTO V_ESTADO
        FROM MATERIALES WHERE ID_MATERIAL = P_ID_MATERIAL;
        IF V_ESTADO = 'DISPONIBLE' THEN RETURN 1; ELSE RETURN 0; END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN 0;
    END FN_MATERIAL_DISPONIBLE;

END PKG_MATERIALES;
/

-- PKG_PRESTAMOS
CREATE OR REPLACE PACKAGE BODY PKG_PRESTAMOS AS

    PROCEDURE REGISTRAR_PRESTAMO(
        P_CEDULA                    IN PRESTAMOS.CEDULA%TYPE,
        P_ID_MATERIAL               IN PRESTAMOS.ID_MATERIAL%TYPE,
        P_FECHA_DEVOLUCION_ESPERADA IN PRESTAMOS.FECHA_DEVOLUCION_ESPERADA%TYPE
    ) IS
        V_ESTADO_USUARIO USUARIOS.ESTADO%TYPE;
        V_ESTADO_MATERIAL MATERIALES.ESTADO%TYPE;
        V_ACTIVOS NUMBER;
    BEGIN
        BEGIN
            SELECT ESTADO INTO V_ESTADO_USUARIO FROM USUARIOS WHERE CEDULA = P_CEDULA;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20030, 'El usuario no existe.');
        END;
        IF V_ESTADO_USUARIO != 'A' THEN
            RAISE_APPLICATION_ERROR(-20031, 'El usuario no esta activo.');
        END IF;

        BEGIN
            SELECT ESTADO INTO V_ESTADO_MATERIAL FROM MATERIALES WHERE ID_MATERIAL = P_ID_MATERIAL;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20032, 'El material no existe.');
        END;
        IF V_ESTADO_MATERIAL != 'DISPONIBLE' THEN
            RAISE_APPLICATION_ERROR(-20033, 'El material no esta disponible.');
        END IF;

        SELECT COUNT(*) INTO V_ACTIVOS FROM PRESTAMOS
        WHERE ID_MATERIAL = P_ID_MATERIAL AND ESTADO = 'ACTIVO';
        IF V_ACTIVOS > 0 THEN
            RAISE_APPLICATION_ERROR(-20034, 'El material ya tiene un prestamo activo.');
        END IF;

        IF P_FECHA_DEVOLUCION_ESPERADA < TRUNC(SYSDATE) THEN
            RAISE_APPLICATION_ERROR(-20035, 'La fecha de devolucion no puede ser anterior a hoy.');
        END IF;

        INSERT INTO PRESTAMOS (ID_PRESTAMO, CEDULA, ID_MATERIAL, FECHA_DEVOLUCION_ESPERADA)
        VALUES (SEQ_PRESTAMOS.NEXTVAL, P_CEDULA, P_ID_MATERIAL, P_FECHA_DEVOLUCION_ESPERADA);

        UPDATE MATERIALES SET ESTADO = 'PRESTADO' WHERE ID_MATERIAL = P_ID_MATERIAL;
    END REGISTRAR_PRESTAMO;

    PROCEDURE REGISTRAR_DEVOLUCION(
        P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE
    ) IS
        V_ESTADO      PRESTAMOS.ESTADO%TYPE;
        V_ID_MATERIAL PRESTAMOS.ID_MATERIAL%TYPE;
    BEGIN
        BEGIN
            SELECT ESTADO, ID_MATERIAL INTO V_ESTADO, V_ID_MATERIAL
            FROM PRESTAMOS WHERE ID_PRESTAMO = P_ID_PRESTAMO;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20036, 'El prestamo no existe.');
        END;
        IF V_ESTADO != 'ACTIVO' THEN
            RAISE_APPLICATION_ERROR(-20037, 'El prestamo ya fue devuelto o anulado.');
        END IF;

        UPDATE PRESTAMOS
        SET FECHA_DEVOLUCION_REAL = SYSDATE, ESTADO = 'DEVUELTO'
        WHERE ID_PRESTAMO = P_ID_PRESTAMO;

        UPDATE MATERIALES SET ESTADO = 'DISPONIBLE' WHERE ID_MATERIAL = V_ID_MATERIAL;
    END REGISTRAR_DEVOLUCION;

    PROCEDURE ANULAR_PRESTAMO(
        P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE
    ) IS
        V_ESTADO      PRESTAMOS.ESTADO%TYPE;
        V_ID_MATERIAL PRESTAMOS.ID_MATERIAL%TYPE;
    BEGIN
        BEGIN
            SELECT ESTADO, ID_MATERIAL INTO V_ESTADO, V_ID_MATERIAL
            FROM PRESTAMOS WHERE ID_PRESTAMO = P_ID_PRESTAMO;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20038, 'El prestamo no existe.');
        END;
        IF V_ESTADO != 'ACTIVO' THEN
            RAISE_APPLICATION_ERROR(-20039, 'Solo se pueden anular prestamos activos.');
        END IF;

        UPDATE PRESTAMOS SET ESTADO = 'ANULADO' WHERE ID_PRESTAMO = P_ID_PRESTAMO;
        UPDATE MATERIALES SET ESTADO = 'DISPONIBLE' WHERE ID_MATERIAL = V_ID_MATERIAL;
    END ANULAR_PRESTAMO;

    PROCEDURE OBTENER_PRESTAMO(
        P_ID_PRESTAMO IN  PRESTAMOS.ID_PRESTAMO%TYPE,
        P_RESULTADO   OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT P.ID_PRESTAMO, P.CEDULA, P.ID_MATERIAL,
                   P.FECHA_PRESTAMO, P.FECHA_DEVOLUCION_ESPERADA,
                   P.FECHA_DEVOLUCION_REAL, P.ESTADO,
                   U.NOMBRE || ' ' || U.APELLIDOS AS NOMBRE_USUARIO,
                   M.TITULO AS TITULO_MATERIAL
            FROM PRESTAMOS P
            JOIN USUARIOS U  ON P.CEDULA = U.CEDULA
            JOIN MATERIALES M ON P.ID_MATERIAL = M.ID_MATERIAL
            WHERE P.ID_PRESTAMO = P_ID_PRESTAMO;
    END OBTENER_PRESTAMO;

    PROCEDURE LISTAR_PRESTAMOS(
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT P.ID_PRESTAMO, P.CEDULA, P.ID_MATERIAL,
                   P.FECHA_PRESTAMO, P.FECHA_DEVOLUCION_ESPERADA,
                   P.FECHA_DEVOLUCION_REAL, P.ESTADO,
                   U.NOMBRE || ' ' || U.APELLIDOS AS NOMBRE_USUARIO,
                   M.TITULO AS TITULO_MATERIAL
            FROM PRESTAMOS P
            JOIN USUARIOS U  ON P.CEDULA = U.CEDULA
            JOIN MATERIALES M ON P.ID_MATERIAL = M.ID_MATERIAL
            ORDER BY P.FECHA_PRESTAMO DESC;
    END LISTAR_PRESTAMOS;

    PROCEDURE LISTAR_PRESTAMOS_ACTIVOS(
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT P.ID_PRESTAMO, P.CEDULA, P.ID_MATERIAL,
                   P.FECHA_PRESTAMO, P.FECHA_DEVOLUCION_ESPERADA,
                   P.FECHA_DEVOLUCION_REAL, P.ESTADO,
                   U.NOMBRE || ' ' || U.APELLIDOS AS NOMBRE_USUARIO,
                   M.TITULO AS TITULO_MATERIAL
            FROM PRESTAMOS P
            JOIN USUARIOS U  ON P.CEDULA = U.CEDULA
            JOIN MATERIALES M ON P.ID_MATERIAL = M.ID_MATERIAL
            WHERE P.ESTADO = 'ACTIVO'
            ORDER BY P.FECHA_PRESTAMO DESC;
    END LISTAR_PRESTAMOS_ACTIVOS;

    PROCEDURE LISTAR_HISTORIAL_USUARIO(
        P_CEDULA    IN  USUARIOS.CEDULA%TYPE,
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT P.ID_PRESTAMO, P.ID_MATERIAL,
                   P.FECHA_PRESTAMO, P.FECHA_DEVOLUCION_ESPERADA,
                   P.FECHA_DEVOLUCION_REAL, P.ESTADO,
                   M.TITULO AS TITULO_MATERIAL
            FROM PRESTAMOS P
            JOIN MATERIALES M ON P.ID_MATERIAL = M.ID_MATERIAL
            WHERE P.CEDULA = P_CEDULA
            ORDER BY P.FECHA_PRESTAMO DESC;
    END LISTAR_HISTORIAL_USUARIO;

    FUNCTION FN_PRESTAMOS_ACTIVOS_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE
    ) RETURN NUMBER IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL FROM PRESTAMOS
        WHERE CEDULA = P_CEDULA AND ESTADO = 'ACTIVO';
        RETURN V_TOTAL;
    END FN_PRESTAMOS_ACTIVOS_USUARIO;

END PKG_PRESTAMOS;
/
