-- Datos de prueba

-- Tipos de material
INSERT INTO TIPOS_MATERIAL VALUES (SEQ_TIPOS_MATERIAL.NEXTVAL, 'Libro',       'Material impreso encuadernado',       'A');
INSERT INTO TIPOS_MATERIAL VALUES (SEQ_TIPOS_MATERIAL.NEXTVAL, 'Revista',     'Publicacion periodica',               'A');
INSERT INTO TIPOS_MATERIAL VALUES (SEQ_TIPOS_MATERIAL.NEXTVAL, 'Periodico',   'Publicacion diaria o semanal',        'A');
INSERT INTO TIPOS_MATERIAL VALUES (SEQ_TIPOS_MATERIAL.NEXTVAL, 'Audiovisual', 'Material en formato de video o audio', 'A');
INSERT INTO TIPOS_MATERIAL VALUES (SEQ_TIPOS_MATERIAL.NEXTVAL, 'Mapa',        'Representacion geografica',           'A');

-- Categorias
INSERT INTO CATEGORIAS VALUES (SEQ_CATEGORIAS.NEXTVAL, 'Literatura',      'Obras literarias y narrativa',       'A');
INSERT INTO CATEGORIAS VALUES (SEQ_CATEGORIAS.NEXTVAL, 'Ciencia Ficcion', 'Ficcion cientifica y futurista',     'A');
INSERT INTO CATEGORIAS VALUES (SEQ_CATEGORIAS.NEXTVAL, 'Historia',        'Documentos y textos historicos',     'A');
INSERT INTO CATEGORIAS VALUES (SEQ_CATEGORIAS.NEXTVAL, 'Tecnologia',      'Informatica, ingenieria y ciencias', 'A');
INSERT INTO CATEGORIAS VALUES (SEQ_CATEGORIAS.NEXTVAL, 'Educacion',       'Material pedagogico y academico',    'A');

-- Usuarios
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO)
VALUES ('101110111', 'Carlos',   'Ramirez Lopez',    'carlos@correo.com',   '8888-1111');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO)
VALUES ('202220222', 'Maria',    'Gonzalez Soto',    'maria@correo.com',    '8888-2222');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO)
VALUES ('303330333', 'Jose',     'Hernandez Mora',   'jose@correo.com',     '8888-3333');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO)
VALUES ('404440444', 'Ana',      'Castro Vargas',    'ana@correo.com',      '8888-4444');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO)
VALUES ('505550555', 'Luis',     'Jimenez Rojas',    'luis@correo.com',     '8888-5555');
INSERT INTO USUARIOS (CEDULA, NOMBRE, APELLIDOS, CORREO, TELEFONO)
VALUES ('606660666', 'Patricia', 'Montero Araya',    'patricia@correo.com', '8888-6666');

-- Materiales
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'El marciano',               'Andy Weir',          'Crown',         2014, '978-0-553-41802-6', 1, 2);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Neuromante',                'William Gibson',     'Ace Books',     1984, '978-0-441-56956-4', 1, 2);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Fundacion',                 'Isaac Asimov',       'Gnome Press',   1951, '978-0-553-29335-7', 1, 2);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Cien anios de soledad',     'Gabriel Garcia M.',  'Sudamericana',  1967, '978-0-06-088328-7', 1, 1);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Don Quijote de la Mancha',  'Miguel de Cervantes','Francisco R.',  1605, '978-84-376-0494-7', 1, 1);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Breve historia del tiempo', 'Stephen Hawking',    'Bantam',        1988, '978-0-553-10953-5', 1, 4);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Clean Code',                'Robert C. Martin',   'Prentice Hall', 2008, '978-0-13-235088-4', 1, 4);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Historia de Costa Rica',    'Ivan Molina',        'EUCR',          2005, '978-9968-46-312-1', 1, 3);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'National Geographic',       'Varios',             'Nat Geo',       2023, NULL,                2, 3);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Revista Tecnologica',       'Varios',             'TechMag',       2024, NULL,                2, 4);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Cosmos: Un viaje personal', 'Carl Sagan',         'PBS',           1980, NULL,                4, 4);
INSERT INTO MATERIALES (ID_MATERIAL, TITULO, AUTOR, EDITORIAL, ANIO_PUBLICACION, CODIGO_ISBN, ID_TIPO_MATERIAL, ID_CATEGORIA)
VALUES (SEQ_MATERIALES.NEXTVAL, 'Mapa de America Central',   'IGN',                'IGN',           2020, NULL,                5, 3);

-- Prestamos
INSERT INTO PRESTAMOS (ID_PRESTAMO, CEDULA, ID_MATERIAL, FECHA_DEVOLUCION_ESPERADA, ESTADO)
VALUES (SEQ_PRESTAMOS.NEXTVAL, '101110111', 1, SYSDATE + 14, 'ACTIVO');
UPDATE MATERIALES SET ESTADO = 'PRESTADO' WHERE ID_MATERIAL = 1;

INSERT INTO PRESTAMOS (ID_PRESTAMO, CEDULA, ID_MATERIAL, FECHA_DEVOLUCION_ESPERADA, ESTADO)
VALUES (SEQ_PRESTAMOS.NEXTVAL, '202220222', 3, SYSDATE + 14, 'ACTIVO');
UPDATE MATERIALES SET ESTADO = 'PRESTADO' WHERE ID_MATERIAL = 3;

INSERT INTO PRESTAMOS (ID_PRESTAMO, CEDULA, ID_MATERIAL, FECHA_PRESTAMO, FECHA_DEVOLUCION_ESPERADA, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES (SEQ_PRESTAMOS.NEXTVAL, '303330333', 4, SYSDATE - 20, SYSDATE - 6, SYSDATE - 7, 'DEVUELTO');

INSERT INTO PRESTAMOS (ID_PRESTAMO, CEDULA, ID_MATERIAL, FECHA_PRESTAMO, FECHA_DEVOLUCION_ESPERADA, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES (SEQ_PRESTAMOS.NEXTVAL, '101110111', 7, SYSDATE - 30, SYSDATE - 16, SYSDATE - 18, 'DEVUELTO');

COMMIT;
