-- Objetos PL/SQL adicionales - Fabio
-- Vistas, funciones y paquetes de consultas y reportes


CREATE OR REPLACE VIEW VW_MATERIALES_DISPONIBLES AS
SELECT
    M.ID_MATERIAL,
    M.TITULO,
    M.AUTOR,
    M.CODIGO_ISBN,
    T.NOMBRE AS TIPO_MATERIAL,
    C.NOMBRE AS CATEGORIA
FROM MATERIALES M
JOIN TIPOS_MATERIAL T ON M.ID_TIPO_MATERIAL = T.ID_TIPO_MATERIAL
JOIN CATEGORIAS C ON M.ID_CATEGORIA = C.ID_CATEGORIA
WHERE M.ESTADO = 'DISPONIBLE'
  AND T.ESTADO = 'A'
  AND C.ESTADO = 'A';
/

CREATE OR REPLACE VIEW VW_MATERIALES_PRESTADOS AS
SELECT
    M.ID_MATERIAL,
    M.TITULO,
    M.AUTOR,
    T.NOMBRE AS TIPO_MATERIAL,
    C.NOMBRE AS CATEGORIA
FROM MATERIALES M
JOIN TIPOS_MATERIAL T ON M.ID_TIPO_MATERIAL = T.ID_TIPO_MATERIAL
JOIN CATEGORIAS C ON M.ID_CATEGORIA = C.ID_CATEGORIA
WHERE M.ESTADO = 'PRESTADO';
/

CREATE OR REPLACE VIEW VW_MATERIALES_INACTIVOS AS
SELECT
    M.ID_MATERIAL,
    M.TITULO,
    M.AUTOR,
    M.CODIGO_ISBN,
    M.ESTADO
FROM MATERIALES M
WHERE M.ESTADO = 'INACTIVO';
/

CREATE OR REPLACE VIEW VW_USUARIOS_ACTIVOS AS
SELECT
    U.CEDULA,
    U.NOMBRE,
    U.APELLIDOS,
    U.CORREO,
    U.TELEFONO,
    U.FECHA_REGISTRO
FROM USUARIOS U
WHERE U.ESTADO = 'A';
/

CREATE OR REPLACE VIEW VW_USUARIOS_INACTIVOS AS
SELECT
    U.CEDULA,
    U.NOMBRE,
    U.APELLIDOS,
    U.CORREO,
    U.TELEFONO,
    U.FECHA_REGISTRO
FROM USUARIOS U
WHERE U.ESTADO = 'I';
/

CREATE OR REPLACE VIEW VW_PRESTAMOS_ACTIVOS AS
SELECT
    P.ID_PRESTAMO,
    P.CEDULA,
    P.ID_MATERIAL,
    P.FECHA_PRESTAMO,
    P.FECHA_DEVOLUCION_ESPERADA,
    U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO,
    M.TITULO AS MATERIAL
FROM PRESTAMOS P
JOIN USUARIOS U ON P.CEDULA = U.CEDULA
JOIN MATERIALES M ON P.ID_MATERIAL = M.ID_MATERIAL
WHERE P.ESTADO = 'ACTIVO';
/

CREATE OR REPLACE VIEW VW_PRESTAMOS_DEVUELTOS AS
SELECT
    P.ID_PRESTAMO,
    P.CEDULA,
    P.ID_MATERIAL,
    P.FECHA_PRESTAMO,
    P.FECHA_DEVOLUCION_ESPERADA,
    P.FECHA_DEVOLUCION_REAL,
    U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO,
    M.TITULO AS MATERIAL
FROM PRESTAMOS P
JOIN USUARIOS U ON P.CEDULA = U.CEDULA
JOIN MATERIALES M ON P.ID_MATERIAL = M.ID_MATERIAL
WHERE P.ESTADO = 'DEVUELTO';
/

CREATE OR REPLACE VIEW VW_PRESTAMOS_VENCIDOS AS
SELECT
    P.ID_PRESTAMO,
    P.CEDULA,
    P.ID_MATERIAL,
    P.FECHA_PRESTAMO,
    P.FECHA_DEVOLUCION_ESPERADA,
    U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO,
    M.TITULO AS MATERIAL
FROM PRESTAMOS P
JOIN USUARIOS U ON P.CEDULA = U.CEDULA
JOIN MATERIALES M ON P.ID_MATERIAL = M.ID_MATERIAL
WHERE P.ESTADO = 'ACTIVO'
  AND P.FECHA_DEVOLUCION_ESPERADA < TRUNC(SYSDATE);
/

CREATE OR REPLACE VIEW VW_RESUMEN_PRESTAMOS AS
SELECT
    U.CEDULA,
    U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO,
    COUNT(P.ID_PRESTAMO) AS TOTAL_PRESTAMOS,
    SUM(CASE WHEN P.ESTADO = 'ACTIVO' THEN 1 ELSE 0 END) AS ACTIVOS,
    SUM(CASE WHEN P.ESTADO = 'DEVUELTO' THEN 1 ELSE 0 END) AS DEVUELTOS,
    SUM(CASE WHEN P.ESTADO = 'ANULADO' THEN 1 ELSE 0 END) AS ANULADOS
FROM USUARIOS U
LEFT JOIN PRESTAMOS P ON U.CEDULA = P.CEDULA
GROUP BY U.CEDULA, U.NOMBRE, U.APELLIDOS;
/

CREATE OR REPLACE VIEW VW_HISTORIAL_MATERIALES AS
SELECT
    P.ID_PRESTAMO,
    U.CEDULA,
    U.NOMBRE || ' ' || U.APELLIDOS AS USUARIO,
    M.TITULO AS MATERIAL,
    P.FECHA_PRESTAMO,
    P.FECHA_DEVOLUCION_ESPERADA,
    P.FECHA_DEVOLUCION_REAL,
    P.ESTADO
FROM PRESTAMOS P
JOIN USUARIOS U ON P.CEDULA = U.CEDULA
JOIN MATERIALES M ON P.ID_MATERIAL = M.ID_MATERIAL;
/

PROMPT Creando paquete PKG_REPORTES...

CREATE OR REPLACE PACKAGE PKG_REPORTES AS

    PROCEDURE REPORTE_MATERIALES_DISPONIBLES(
        P_RESULTADO OUT SYS_REFCURSOR
    );

    PROCEDURE REPORTE_PRESTAMOS_VENCIDOS(
        P_RESULTADO OUT SYS_REFCURSOR
    );

    PROCEDURE MARCAR_PRESTAMOS_VENCIDOS;

    FUNCTION FN_TOTAL_MATERIALES_DISPONIBLES RETURN NUMBER;
    FUNCTION FN_TOTAL_PRESTAMOS_ACTIVOS RETURN NUMBER;
    FUNCTION FN_TOTAL_USUARIOS_ACTIVOS RETURN NUMBER;
    FUNCTION FN_PRESTAMOS_VENCIDOS RETURN NUMBER;
    FUNCTION FN_TOTAL_MATERIALES_POR_TIPO(
        P_ID_TIPO_MATERIAL IN TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE
    ) RETURN NUMBER;
    FUNCTION FN_DIAS_RETRASO(
        P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE
    ) RETURN NUMBER;
    FUNCTION FN_MATERIAL_MAS_PRESTADO RETURN NUMBER;

END PKG_REPORTES;
/

CREATE OR REPLACE PACKAGE BODY PKG_REPORTES AS

    PROCEDURE REPORTE_MATERIALES_DISPONIBLES(
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT *
            FROM VW_MATERIALES_DISPONIBLES
            ORDER BY TITULO;
    END REPORTE_MATERIALES_DISPONIBLES;

    PROCEDURE REPORTE_PRESTAMOS_VENCIDOS(
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT *
            FROM VW_PRESTAMOS_VENCIDOS
            ORDER BY FECHA_DEVOLUCION_ESPERADA;
    END REPORTE_PRESTAMOS_VENCIDOS;

    PROCEDURE MARCAR_PRESTAMOS_VENCIDOS IS
        CURSOR C_VENCIDOS IS
            SELECT ID_PRESTAMO
            FROM PRESTAMOS
            WHERE ESTADO = 'ACTIVO'
              AND FECHA_DEVOLUCION_ESPERADA < TRUNC(SYSDATE);
    BEGIN
        FOR REG IN C_VENCIDOS LOOP
            UPDATE PRESTAMOS
            SET ESTADO = 'ANULADO'
            WHERE ID_PRESTAMO = REG.ID_PRESTAMO;
        END LOOP;
    END MARCAR_PRESTAMOS_VENCIDOS;

    FUNCTION FN_TOTAL_MATERIALES_DISPONIBLES RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_DISPONIBLES IS
            SELECT ID_MATERIAL
            FROM MATERIALES
            WHERE ESTADO = 'DISPONIBLE';
    BEGIN
        FOR REG IN C_DISPONIBLES LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_MATERIALES_DISPONIBLES;

    FUNCTION FN_TOTAL_PRESTAMOS_ACTIVOS RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_ACTIVOS IS
            SELECT ID_PRESTAMO
            FROM PRESTAMOS
            WHERE ESTADO = 'ACTIVO';
    BEGIN
        FOR REG IN C_ACTIVOS LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_PRESTAMOS_ACTIVOS;

    FUNCTION FN_TOTAL_USUARIOS_ACTIVOS RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_USUARIOS IS
            SELECT CEDULA
            FROM USUARIOS
            WHERE ESTADO = 'A';
    BEGIN
        FOR REG IN C_USUARIOS LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_USUARIOS_ACTIVOS;

    FUNCTION FN_PRESTAMOS_VENCIDOS RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_VENCIDOS IS
            SELECT ID_PRESTAMO
            FROM PRESTAMOS
            WHERE ESTADO = 'ACTIVO'
              AND FECHA_DEVOLUCION_ESPERADA < TRUNC(SYSDATE);
    BEGIN
        FOR REG IN C_VENCIDOS LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_PRESTAMOS_VENCIDOS;

    FUNCTION FN_TOTAL_MATERIALES_POR_TIPO(
        P_ID_TIPO_MATERIAL IN TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE
    ) RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_TIPO IS
            SELECT ID_MATERIAL
            FROM MATERIALES
            WHERE ID_TIPO_MATERIAL = P_ID_TIPO_MATERIAL;
    BEGIN
        FOR REG IN C_TIPO LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_MATERIALES_POR_TIPO;

    FUNCTION FN_DIAS_RETRASO(
        P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE
    ) RETURN NUMBER IS
        V_DIAS NUMBER := 0;
        CURSOR C_PRESTAMO IS
            SELECT FECHA_DEVOLUCION_ESPERADA, FECHA_DEVOLUCION_REAL
            FROM PRESTAMOS
            WHERE ID_PRESTAMO = P_ID_PRESTAMO;
    BEGIN
        FOR REG IN C_PRESTAMO LOOP
            IF REG.FECHA_DEVOLUCION_REAL IS NOT NULL THEN
                V_DIAS := TRUNC(REG.FECHA_DEVOLUCION_REAL - REG.FECHA_DEVOLUCION_ESPERADA);
            ELSE
                V_DIAS := TRUNC(SYSDATE - REG.FECHA_DEVOLUCION_ESPERADA);
            END IF;
        END LOOP;
        RETURN NVL(V_DIAS, 0);
    END FN_DIAS_RETRASO;

    FUNCTION FN_MATERIAL_MAS_PRESTADO RETURN NUMBER IS
        V_ID_MATERIAL NUMBER := NULL;
        CURSOR C_MAS_PRESTADO IS
            SELECT ID_MATERIAL
            FROM (
                SELECT ID_MATERIAL, COUNT(*) AS CNT
                FROM PRESTAMOS
                GROUP BY ID_MATERIAL
            )
            WHERE CNT = (
                SELECT MAX(CNT)
                FROM (
                    SELECT COUNT(*) AS CNT
                    FROM PRESTAMOS
                    GROUP BY ID_MATERIAL
                )
            );
    BEGIN
        FOR REG IN C_MAS_PRESTADO LOOP
            V_ID_MATERIAL := REG.ID_MATERIAL;
            EXIT;
        END LOOP;
        RETURN V_ID_MATERIAL;
    END FN_MATERIAL_MAS_PRESTADO;

END PKG_REPORTES;
/

PROMPT Creando paquete PKG_CONSULTAS...

CREATE OR REPLACE PACKAGE PKG_CONSULTAS AS

    PROCEDURE CONSULTAR_MATERIALES_POR_CATEGORIA(
        P_ID_CATEGORIA IN CATEGORIAS.ID_CATEGORIA%TYPE,
        P_RESULTADO OUT SYS_REFCURSOR
    );

    PROCEDURE CONSULTAR_HISTORIAL_POR_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE,
        P_RESULTADO OUT SYS_REFCURSOR
    );

    FUNCTION FN_TOTAL_MATERIALES_POR_TIPO(
        P_ID_TIPO_MATERIAL IN TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE
    ) RETURN NUMBER;
    FUNCTION FN_TOTAL_PRESTAMOS_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE
    ) RETURN NUMBER;
    FUNCTION FN_EXISTE_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE
    ) RETURN NUMBER;
    FUNCTION FN_TOTAL_MATERIALES_INACTIVOS RETURN NUMBER;
    FUNCTION FN_TOTAL_PRESTAMOS_DEVUELTOS RETURN NUMBER;

END PKG_CONSULTAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_CONSULTAS AS

    PROCEDURE CONSULTAR_MATERIALES_POR_CATEGORIA(
        P_ID_CATEGORIA IN CATEGORIAS.ID_CATEGORIA%TYPE,
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT *
            FROM VW_MATERIALES_DISPONIBLES
            WHERE CATEGORIA = (
                SELECT NOMBRE
                FROM CATEGORIAS
                WHERE ID_CATEGORIA = P_ID_CATEGORIA
            );
    END CONSULTAR_MATERIALES_POR_CATEGORIA;

    PROCEDURE CONSULTAR_HISTORIAL_POR_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE,
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT *
            FROM VW_HISTORIAL_MATERIALES
            WHERE CEDULA = P_CEDULA
            ORDER BY FECHA_PRESTAMO DESC;
    END CONSULTAR_HISTORIAL_POR_USUARIO;

    FUNCTION FN_TOTAL_MATERIALES_POR_TIPO(
        P_ID_TIPO_MATERIAL IN TIPOS_MATERIAL.ID_TIPO_MATERIAL%TYPE
    ) RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_TIPO IS
            SELECT ID_MATERIAL
            FROM MATERIALES
            WHERE ID_TIPO_MATERIAL = P_ID_TIPO_MATERIAL;
    BEGIN
        FOR REG IN C_TIPO LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_MATERIALES_POR_TIPO;

    FUNCTION FN_TOTAL_PRESTAMOS_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE
    ) RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_USUARIO IS
            SELECT ID_PRESTAMO
            FROM PRESTAMOS
            WHERE CEDULA = P_CEDULA;
    BEGIN
        FOR REG IN C_USUARIO LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_PRESTAMOS_USUARIO;

    FUNCTION FN_EXISTE_USUARIO(
        P_CEDULA IN USUARIOS.CEDULA%TYPE
    ) RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_USUARIO IS
            SELECT CEDULA
            FROM USUARIOS
            WHERE CEDULA = P_CEDULA;
    BEGIN
        FOR REG IN C_USUARIO LOOP
            V_TOTAL := 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_EXISTE_USUARIO;

    FUNCTION FN_TOTAL_MATERIALES_INACTIVOS RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_INACTIVOS IS
            SELECT ID_MATERIAL
            FROM MATERIALES
            WHERE ESTADO = 'INACTIVO';
    BEGIN
        FOR REG IN C_INACTIVOS LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_MATERIALES_INACTIVOS;

    FUNCTION FN_TOTAL_PRESTAMOS_DEVUELTOS RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_DEVUELTOS IS
            SELECT ID_PRESTAMO
            FROM PRESTAMOS
            WHERE ESTADO = 'DEVUELTO';
    BEGIN
        FOR REG IN C_DEVUELTOS LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_PRESTAMOS_DEVUELTOS;

END PKG_CONSULTAS;
/

