-- Objetos PL/SQL adicionales - Jose
-- Paquetes de validaciones/auditoria/multas, funciones y triggers

-- ============================================================
-- TABLAS Y SECUENCIAS NUEVAS
-- ============================================================

CREATE TABLE MULTAS (
    ID_MULTA          NUMBER        PRIMARY KEY,
    ID_PRESTAMO       NUMBER        NOT NULL,
    CEDULA            VARCHAR2(20)  NOT NULL,
    MONTO             NUMBER(10,2)  NOT NULL,
    DIAS_ATRASO       NUMBER        NOT NULL,
    FECHA_GENERACION  DATE          DEFAULT SYSDATE NOT NULL,
    ESTADO_PAGO       VARCHAR2(15)  DEFAULT 'PENDIENTE' NOT NULL,
    CONSTRAINT CK_MULTAS_ESTADO   CHECK (ESTADO_PAGO IN ('PENDIENTE','PAGADA')),
    CONSTRAINT FK_MULTA_PRESTAMO  FOREIGN KEY (ID_PRESTAMO) REFERENCES PRESTAMOS(ID_PRESTAMO),
    CONSTRAINT FK_MULTA_USUARIO   FOREIGN KEY (CEDULA)      REFERENCES USUARIOS(CEDULA)
);
CREATE SEQUENCE SEQ_MULTAS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE AUDITORIA_LOG (
    ID_LOG           NUMBER        PRIMARY KEY,
    TABLA_AFECTADA   VARCHAR2(30)  NOT NULL,
    OPERACION        VARCHAR2(10)  NOT NULL,
    USUARIO_DB       VARCHAR2(30)  DEFAULT USER NOT NULL,
    FECHA_HORA       DATE          DEFAULT SYSDATE NOT NULL,
    DETALLE          VARCHAR2(4000)
);
CREATE SEQUENCE SEQ_AUDITORIA_LOG START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- PKG_VALIDACIONES
-- ============================================================

CREATE OR REPLACE PACKAGE PKG_VALIDACIONES AS
    FUNCTION FN_USUARIO_ACTIVO(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER;
    FUNCTION FN_LIMITE_PRESTAMOS_SUPERADO(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER;
    FUNCTION FN_USUARIO_CON_MULTAS_PENDIENTES(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER;
    PROCEDURE VALIDAR_PRESTAMO(
        P_CEDULA    IN  USUARIOS.CEDULA%TYPE,
        P_RESULTADO OUT VARCHAR2
    );
END PKG_VALIDACIONES;
/

CREATE OR REPLACE PACKAGE BODY PKG_VALIDACIONES AS

    FUNCTION FN_USUARIO_ACTIVO(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_USUARIO IS
            SELECT CEDULA FROM USUARIOS WHERE CEDULA = P_CEDULA AND ESTADO = 'A';
    BEGIN
        FOR REG IN C_USUARIO LOOP
            V_TOTAL := 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_USUARIO_ACTIVO;

    FUNCTION FN_LIMITE_PRESTAMOS_SUPERADO(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER IS
    BEGIN
        -- Reutiliza la funcion que ya existe en PKG_PRESTAMOS (de Marco)
        IF PKG_PRESTAMOS.FN_PRESTAMOS_ACTIVOS_USUARIO(P_CEDULA) >= 3 THEN
            RETURN 1;
        ELSE
            RETURN 0;
        END IF;
    END FN_LIMITE_PRESTAMOS_SUPERADO;

    FUNCTION FN_USUARIO_CON_MULTAS_PENDIENTES(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_MULTAS IS
            SELECT ID_MULTA FROM MULTAS
            WHERE CEDULA = P_CEDULA AND ESTADO_PAGO = 'PENDIENTE';
    BEGIN
        FOR REG IN C_MULTAS LOOP
            V_TOTAL := 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_USUARIO_CON_MULTAS_PENDIENTES;

    PROCEDURE VALIDAR_PRESTAMO(
        P_CEDULA    IN  USUARIOS.CEDULA%TYPE,
        P_RESULTADO OUT VARCHAR2
    ) IS
    BEGIN
        IF FN_USUARIO_ACTIVO(P_CEDULA) = 0 THEN
            P_RESULTADO := 'USUARIO_INACTIVO_O_NO_EXISTE';
        ELSIF FN_USUARIO_CON_MULTAS_PENDIENTES(P_CEDULA) = 1 THEN
            P_RESULTADO := 'USUARIO_CON_MULTAS_PENDIENTES';
        ELSIF FN_LIMITE_PRESTAMOS_SUPERADO(P_CEDULA) = 1 THEN
            P_RESULTADO := 'LIMITE_DE_PRESTAMOS_ALCANZADO';
        ELSE
            P_RESULTADO := 'OK';
        END IF;
    END VALIDAR_PRESTAMO;

END PKG_VALIDACIONES;
/

-- ============================================================
-- PKG_AUDITORIA
-- ============================================================

CREATE OR REPLACE PACKAGE PKG_AUDITORIA AS
    PROCEDURE REGISTRAR_EVENTO(
        P_TABLA     IN VARCHAR2,
        P_OPERACION IN VARCHAR2,
        P_DETALLE   IN VARCHAR2
    );
    PROCEDURE LISTAR_CAMBIOS_TABLA(
        P_TABLA     IN  VARCHAR2,
        P_TOTAL     OUT NUMBER,
        P_RESULTADO OUT SYS_REFCURSOR
    );
    PROCEDURE PURGAR_AUDITORIA(P_DIAS IN NUMBER);
    FUNCTION FN_TOTAL_EVENTOS_TABLA(P_TABLA IN VARCHAR2) RETURN NUMBER;
END PKG_AUDITORIA;
/

CREATE OR REPLACE PACKAGE BODY PKG_AUDITORIA AS

    PROCEDURE REGISTRAR_EVENTO(
        P_TABLA     IN VARCHAR2,
        P_OPERACION IN VARCHAR2,
        P_DETALLE   IN VARCHAR2
    ) IS
    BEGIN
        INSERT INTO AUDITORIA_LOG (ID_LOG, TABLA_AFECTADA, OPERACION, USUARIO_DB, FECHA_HORA, DETALLE)
        VALUES (SEQ_AUDITORIA_LOG.NEXTVAL, P_TABLA, P_OPERACION, USER, SYSDATE, P_DETALLE);
    END REGISTRAR_EVENTO;

    PROCEDURE LISTAR_CAMBIOS_TABLA(
        P_TABLA     IN  VARCHAR2,
        P_TOTAL     OUT NUMBER,
        P_RESULTADO OUT SYS_REFCURSOR
    ) IS
        CURSOR C_LOGS IS
            SELECT ID_LOG FROM AUDITORIA_LOG WHERE TABLA_AFECTADA = P_TABLA;
    BEGIN
        P_TOTAL := 0;
        FOR REG IN C_LOGS LOOP
            P_TOTAL := P_TOTAL + 1;
        END LOOP;

        OPEN P_RESULTADO FOR
            SELECT TABLA_AFECTADA, OPERACION, USUARIO_DB, FECHA_HORA, DETALLE
            FROM AUDITORIA_LOG
            WHERE TABLA_AFECTADA = P_TABLA
            ORDER BY FECHA_HORA DESC;
    END LISTAR_CAMBIOS_TABLA;

    PROCEDURE PURGAR_AUDITORIA(P_DIAS IN NUMBER) IS
        CURSOR C_ANTIGUOS IS
            SELECT ID_LOG FROM AUDITORIA_LOG WHERE FECHA_HORA < SYSDATE - P_DIAS;
    BEGIN
        FOR REG IN C_ANTIGUOS LOOP
            DELETE FROM AUDITORIA_LOG WHERE ID_LOG = REG.ID_LOG;
        END LOOP;
    END PURGAR_AUDITORIA;

    FUNCTION FN_TOTAL_EVENTOS_TABLA(P_TABLA IN VARCHAR2) RETURN NUMBER IS
        V_TOTAL NUMBER := 0;
        CURSOR C_EVENTOS IS
            SELECT ID_LOG FROM AUDITORIA_LOG WHERE TABLA_AFECTADA = P_TABLA;
    BEGIN
        FOR REG IN C_EVENTOS LOOP
            V_TOTAL := V_TOTAL + 1;
        END LOOP;
        RETURN V_TOTAL;
    END FN_TOTAL_EVENTOS_TABLA;

END PKG_AUDITORIA;
/

-- ============================================================
-- PKG_MULTAS_ATRASOS
-- ============================================================

CREATE OR REPLACE PACKAGE PKG_MULTAS_ATRASOS AS
    FUNCTION FN_CALCULAR_DIAS_ATRASO(P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE) RETURN NUMBER;
    PROCEDURE GENERAR_MULTA(P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE);
    PROCEDURE GENERAR_MULTA_DIRECTA(
        P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE,
        P_CEDULA      IN PRESTAMOS.CEDULA%TYPE,
        P_DIAS        IN NUMBER
    );
    PROCEDURE GENERAR_MULTAS_AUTOMATICAS;
    PROCEDURE LISTAR_MULTAS_PENDIENTES(P_RESULTADO OUT SYS_REFCURSOR);
    PROCEDURE PAGAR_MULTA(P_ID_MULTA IN MULTAS.ID_MULTA%TYPE);
END PKG_MULTAS_ATRASOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_MULTAS_ATRASOS AS

    FUNCTION FN_CALCULAR_DIAS_ATRASO(P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE) RETURN NUMBER IS
        CURSOR C_PRESTAMO IS
            SELECT FECHA_DEVOLUCION_ESPERADA,
                   NVL(FECHA_DEVOLUCION_REAL, SYSDATE) AS FECHA_COMPARAR
            FROM PRESTAMOS WHERE ID_PRESTAMO = P_ID_PRESTAMO;
        V_PRESTAMO C_PRESTAMO%ROWTYPE;
        V_DIAS NUMBER := 0;
    BEGIN
        OPEN C_PRESTAMO;
        FETCH C_PRESTAMO INTO V_PRESTAMO;
        CLOSE C_PRESTAMO;

        V_DIAS := TRUNC(V_PRESTAMO.FECHA_COMPARAR) - TRUNC(V_PRESTAMO.FECHA_DEVOLUCION_ESPERADA);
        IF V_DIAS < 0 THEN
            V_DIAS := 0;
        END IF;
        RETURN V_DIAS;
    END FN_CALCULAR_DIAS_ATRASO;

    -- Uso normal (fuera de triggers): consulta PRESTAMOS directamente
    PROCEDURE GENERAR_MULTA(P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE) IS
        V_DIAS   NUMBER;
        V_CEDULA PRESTAMOS.CEDULA%TYPE;
        V_MONTO_POR_DIA CONSTANT NUMBER := 500;
        V_YA_EXISTE NUMBER := 0;
        CURSOR C_EXISTENTE IS
            SELECT ID_MULTA FROM MULTAS WHERE ID_PRESTAMO = P_ID_PRESTAMO;
    BEGIN
        FOR REG IN C_EXISTENTE LOOP
            V_YA_EXISTE := 1;
        END LOOP;
        IF V_YA_EXISTE = 1 THEN
            RETURN;
        END IF;

        V_DIAS := FN_CALCULAR_DIAS_ATRASO(P_ID_PRESTAMO);
        IF V_DIAS > 0 THEN
            SELECT CEDULA INTO V_CEDULA FROM PRESTAMOS WHERE ID_PRESTAMO = P_ID_PRESTAMO;
            INSERT INTO MULTAS (ID_MULTA, ID_PRESTAMO, CEDULA, MONTO, DIAS_ATRASO, FECHA_GENERACION, ESTADO_PAGO)
            VALUES (SEQ_MULTAS.NEXTVAL, P_ID_PRESTAMO, V_CEDULA, V_DIAS * V_MONTO_POR_DIA, V_DIAS, SYSDATE, 'PENDIENTE');
        END IF;
    END GENERAR_MULTA;

    -- Version "directa": NO consulta PRESTAMOS (recibe los datos ya calculados).
    PROCEDURE GENERAR_MULTA_DIRECTA(
        P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE,
        P_CEDULA      IN PRESTAMOS.CEDULA%TYPE,
        P_DIAS        IN NUMBER
    ) IS
        V_MONTO_POR_DIA CONSTANT NUMBER := 500;
        V_YA_EXISTE NUMBER := 0;
        CURSOR C_EXISTENTE_DIRECTA IS
            SELECT ID_MULTA FROM MULTAS WHERE ID_PRESTAMO = P_ID_PRESTAMO;
    BEGIN
        FOR REG IN C_EXISTENTE_DIRECTA LOOP
            V_YA_EXISTE := 1;
        END LOOP;

        IF V_YA_EXISTE = 0 AND P_DIAS > 0 THEN
            INSERT INTO MULTAS (ID_MULTA, ID_PRESTAMO, CEDULA, MONTO, DIAS_ATRASO, FECHA_GENERACION, ESTADO_PAGO)
            VALUES (SEQ_MULTAS.NEXTVAL, P_ID_PRESTAMO, P_CEDULA, P_DIAS * V_MONTO_POR_DIA, P_DIAS, SYSDATE, 'PENDIENTE');
        END IF;
    END GENERAR_MULTA_DIRECTA;

    PROCEDURE GENERAR_MULTAS_AUTOMATICAS IS
        CURSOR C_ATRASADOS IS
            SELECT ID_PRESTAMO FROM PRESTAMOS
            WHERE ESTADO = 'ACTIVO' AND FECHA_DEVOLUCION_ESPERADA < TRUNC(SYSDATE);
    BEGIN
        FOR REG IN C_ATRASADOS LOOP
            GENERAR_MULTA(REG.ID_PRESTAMO);
        END LOOP;
    END GENERAR_MULTAS_AUTOMATICAS;

    PROCEDURE LISTAR_MULTAS_PENDIENTES(P_RESULTADO OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN P_RESULTADO FOR
            SELECT M.ID_MULTA, M.CEDULA, U.NOMBRE, U.APELLIDOS, M.MONTO, M.DIAS_ATRASO
            FROM MULTAS M
            JOIN USUARIOS U ON U.CEDULA = M.CEDULA
            WHERE M.ESTADO_PAGO = 'PENDIENTE';
    END LISTAR_MULTAS_PENDIENTES;

    PROCEDURE PAGAR_MULTA(P_ID_MULTA IN MULTAS.ID_MULTA%TYPE) IS
    BEGIN
        UPDATE MULTAS SET ESTADO_PAGO = 'PAGADA' WHERE ID_MULTA = P_ID_MULTA;
    END PAGAR_MULTA;

END PKG_MULTAS_ATRASOS;
/

-- ============================================================
-- 6 FUNCIONES INDEPENDIENTES
-- ============================================================

CREATE OR REPLACE FUNCTION FN_TOTAL_MULTAS_USUARIO(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    CURSOR C_MULTAS_USUARIO IS
        SELECT ID_MULTA FROM MULTAS WHERE CEDULA = P_CEDULA;
BEGIN
    FOR REG IN C_MULTAS_USUARIO LOOP
        V_TOTAL := V_TOTAL + 1;
    END LOOP;
    RETURN V_TOTAL;
END FN_TOTAL_MULTAS_USUARIO;
/

CREATE OR REPLACE FUNCTION FN_MONTO_TOTAL_MULTAS_PENDIENTES(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER IS
    V_MONTO NUMBER;
BEGIN
    SELECT NVL(SUM(MONTO), 0) INTO V_MONTO
    FROM MULTAS WHERE CEDULA = P_CEDULA AND ESTADO_PAGO = 'PENDIENTE';
    RETURN V_MONTO;
END FN_MONTO_TOTAL_MULTAS_PENDIENTES;
/

CREATE OR REPLACE FUNCTION FN_PROMEDIO_DIAS_PRESTAMO RETURN NUMBER IS
    V_PROMEDIO NUMBER;
BEGIN
    SELECT NVL(ROUND(AVG(FECHA_DEVOLUCION_REAL - FECHA_PRESTAMO), 1), 0) INTO V_PROMEDIO
    FROM PRESTAMOS WHERE FECHA_DEVOLUCION_REAL IS NOT NULL;
    RETURN V_PROMEDIO;
END FN_PROMEDIO_DIAS_PRESTAMO;
/

CREATE OR REPLACE FUNCTION FN_DIAS_RESTANTES_PRESTAMO(P_ID_PRESTAMO IN PRESTAMOS.ID_PRESTAMO%TYPE) RETURN NUMBER IS
    V_FECHA_ESPERADA PRESTAMOS.FECHA_DEVOLUCION_ESPERADA%TYPE;
BEGIN
    SELECT FECHA_DEVOLUCION_ESPERADA INTO V_FECHA_ESPERADA
    FROM PRESTAMOS WHERE ID_PRESTAMO = P_ID_PRESTAMO;
    RETURN TRUNC(V_FECHA_ESPERADA) - TRUNC(SYSDATE);
END FN_DIAS_RESTANTES_PRESTAMO;
/

CREATE OR REPLACE FUNCTION FN_PORCENTAJE_MATERIALES_DISPONIBLES RETURN NUMBER IS
    V_TOTAL       NUMBER;
    V_DISPONIBLES NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM MATERIALES;
    IF V_TOTAL = 0 THEN
        RETURN 0;
    END IF;
    SELECT COUNT(*) INTO V_DISPONIBLES FROM MATERIALES WHERE ESTADO = 'DISPONIBLE';
    RETURN ROUND((V_DISPONIBLES / V_TOTAL) * 100, 1);
END FN_PORCENTAJE_MATERIALES_DISPONIBLES;
/

CREATE OR REPLACE FUNCTION FN_ANTIGUEDAD_USUARIO_DIAS(P_CEDULA IN USUARIOS.CEDULA%TYPE) RETURN NUMBER IS
    V_FECHA_REGISTRO USUARIOS.FECHA_REGISTRO%TYPE;
BEGIN
    SELECT FECHA_REGISTRO INTO V_FECHA_REGISTRO FROM USUARIOS WHERE CEDULA = P_CEDULA;
    RETURN TRUNC(SYSDATE) - TRUNC(V_FECHA_REGISTRO);
END FN_ANTIGUEDAD_USUARIO_DIAS;
/

-- ============================================================
-- 5 TRIGGERS
-- ============================================================

-- 1. Impide borrar un usuario que tiene prestamos activos
CREATE OR REPLACE TRIGGER TRG_BLOQUEAR_BAJA_USUARIO_CON_PRESTAMOS
BEFORE DELETE ON USUARIOS
FOR EACH ROW
DECLARE
    CURSOR C_PRESTAMOS_ACTIVOS IS
        SELECT ID_PRESTAMO FROM PRESTAMOS
        WHERE CEDULA = :OLD.CEDULA AND ESTADO = 'ACTIVO';
    V_EXISTE NUMBER := 0;
BEGIN
    FOR REG IN C_PRESTAMOS_ACTIVOS LOOP
        V_EXISTE := 1;
        EXIT;
    END LOOP;
    IF V_EXISTE = 1 THEN
        RAISE_APPLICATION_ERROR(-20040, 'No se puede eliminar un usuario con prestamos activos.');
    END IF;
END;
/

-- 2. Valida que la fecha esperada sea posterior a la fecha del prestamo (defensa extra a nivel de tabla)
CREATE OR REPLACE TRIGGER TRG_VALIDAR_FECHAS_PRESTAMO
BEFORE INSERT ON PRESTAMOS
FOR EACH ROW
BEGIN
    IF :NEW.FECHA_DEVOLUCION_ESPERADA <= :NEW.FECHA_PRESTAMO THEN
        RAISE_APPLICATION_ERROR(-20041, 'La fecha esperada de devolucion debe ser posterior a la fecha del prestamo.');
    END IF;
END;
/

-- 3. Genera la multa automaticamente cuando se registra la devolucion tardia
CREATE OR REPLACE TRIGGER TRG_GENERAR_MULTA_AUTOMATICA
AFTER UPDATE OF FECHA_DEVOLUCION_REAL ON PRESTAMOS
FOR EACH ROW
WHEN (NEW.FECHA_DEVOLUCION_REAL IS NOT NULL)
DECLARE
    V_DIAS NUMBER;
BEGIN
    V_DIAS := TRUNC(:NEW.FECHA_DEVOLUCION_REAL) - TRUNC(:NEW.FECHA_DEVOLUCION_ESPERADA);
    IF V_DIAS > 0 THEN
        PKG_MULTAS_ATRASOS.GENERAR_MULTA_DIRECTA(:NEW.ID_PRESTAMO, :NEW.CEDULA, V_DIAS);
    END IF;
END;
/

-- 4. Auditoria de cambios en USUARIOS
CREATE OR REPLACE TRIGGER TRG_AUDITORIA_USUARIOS
AFTER INSERT OR UPDATE OR DELETE ON USUARIOS
FOR EACH ROW
DECLARE
    V_OPERACION VARCHAR2(10);
BEGIN
    IF INSERTING THEN V_OPERACION := 'INSERT';
    ELSIF UPDATING THEN V_OPERACION := 'UPDATE';
    ELSE V_OPERACION := 'DELETE';
    END IF;

    PKG_AUDITORIA.REGISTRAR_EVENTO('USUARIOS', V_OPERACION,
        'Cedula afectada: ' || NVL(:NEW.CEDULA, :OLD.CEDULA));
END;
/

-- 5. Auditoria de cambios en MATERIALES
CREATE OR REPLACE TRIGGER TRG_AUDITORIA_MATERIALES
AFTER INSERT OR UPDATE OR DELETE ON MATERIALES
FOR EACH ROW
DECLARE
    V_OPERACION VARCHAR2(10);
BEGIN
    IF INSERTING THEN V_OPERACION := 'INSERT';
    ELSIF UPDATING THEN V_OPERACION := 'UPDATE';
    ELSE V_OPERACION := 'DELETE';
    END IF;

    PKG_AUDITORIA.REGISTRAR_EVENTO('MATERIALES', V_OPERACION,
        'ID material afectado: ' || NVL(:NEW.ID_MATERIAL, :OLD.ID_MATERIAL));
END;
/